#!/usr/bin/env node
/*
Scheduled lore drop sender (Telegram).
- Reads data/scroll_index.json (generated by index rebuild workflow)
- Picks a deterministic scroll based on date + slot (no repo write required)
- Sends a short formatted message to Telegram

Env:
- TELEGRAM_TOKEN
- TELEGRAM_CHAT_ID
- DROP_SLOT (0..3) optional
- SCROLL_INDEX (path) optional
*/

const fs = require('fs');
const path = require('path');
const axios = require('axios');

function fail(msg) {
  console.error(msg);
  process.exit(1);
}

function dayKeyUTC(d) {
  // YYYY-MM-DD
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(d.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

function fnv1a32(str) {
  // Small deterministic hash
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

function pickItem(items, slot) {
  const now = new Date();
  const key = `${dayKeyUTC(now)}::slot=${slot}`;
  const idx = fnv1a32(key) % items.length;
  return { item: items[idx], key, idx };
}

function formatMessage({ item, slot }) {
  const title = (item.title || 'Untitled').trim();
  const date = (item.date || '').trim();
  const summary = (item.summary || item.text_preview || '').trim();

  const short = summary.length > 700 ? summary.slice(0, 700).trimEnd() + '…' : summary;
  const source = item.id || item.path || 'unknown';

  const slotNames = ['Dawn Drop', 'Midday Drop', 'Evening Drop', 'Night Drop'];
  const slotLabel = slotNames[slot] || `Drop ${slot}`;

  const lines = [
    `🪷 ${slotLabel}`,
    '',
    `*${escapeMd(title)}*${date ? `  _(${escapeMd(date)})_` : ''}`,
    '',
    escapeMd(short),
    '',
    `Source: \`${escapeMd(source)}\``
  ];

  return lines.join('\n');
}

function escapeMd(s) {
  // Telegram MarkdownV2 escaping (minimal set)
  return String(s || '').replace(/([_\-*\[\]()~`>#+=|{}.!\\])/g, '\\$1');
}

async function sendTelegram(token, chatId, text) {
  const url = `https://api.telegram.org/bot${token}/sendMessage`;
  await axios.post(url, {
    chat_id: chatId,
    text,
    parse_mode: 'MarkdownV2',
    disable_web_page_preview: true
  }, { timeout: 20000 });
}

async function main() {
  const token = process.env.TELEGRAM_TOKEN;
  const chatId = process.env.TELEGRAM_CHAT_ID;
  if (!token) fail('Missing TELEGRAM_TOKEN');
  if (!chatId) fail('Missing TELEGRAM_CHAT_ID');

  const slot = Number.isFinite(parseInt(process.env.DROP_SLOT, 10)) ? parseInt(process.env.DROP_SLOT, 10) : 0;

  const idxPath = process.env.SCROLL_INDEX || path.join(process.cwd(), 'data', 'scroll_index.json');
  if (!fs.existsSync(idxPath)) fail(`Missing scroll index: ${idxPath} (run index rebuild first)`);

  let items;
  try {
    items = JSON.parse(fs.readFileSync(idxPath, 'utf8'));
  } catch (e) {
    fail(`Could not parse scroll index JSON: ${e.message}`);
  }

  if (!Array.isArray(items) || items.length === 0) fail('scroll_index.json is empty or invalid');

  const { item } = pickItem(items, slot);
  const text = formatMessage({ item, slot });
  await sendTelegram(token, chatId, text);

  console.log(`Sent Telegram lore drop (slot=${slot}) using ${item.id || item.path}`);
}

main().catch((e) => {
  console.error('FAILED:', e?.message || e);
  process.exit(1);
});
