#!/usr/bin/env node
/*
Scheduled lore drop sender (Telegram).
- Reads data/scroll_index.json (generated by index rebuild workflow)
- Picks a deterministic scroll based on date + slot (no repo write required)
- Sends a short formatted message to Telegram

Env:
- TELEGRAM_TOKEN
- TELEGRAM_CHAT_ID
- DROP_SLOT (0..3) optional
- SCROLL_INDEX (path) optional
*/

const fs = require('fs');
const path = require('path');
const axios = require('axios');

function fail(msg) {
  console.error(msg);
  process.exit(1);
}

function dayKeyUTC(d) {
  // YYYY-MM-DD
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(d.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

function fnv1a32(str) {
  // Small deterministic hash
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

function pickItem(items, slot) {
  const now = new Date();
  const key = `${dayKeyUTC(now)}::slot=${slot}`;
  const idx = fnv1a32(key) % items.length;
  return { item: items[idx], key, idx };
}

function formatMessage({ item, slot }) {
  const title = (item.title || item.id || 'Untitled').trim();
  const date = (item.date || '').trim();

  const isToadgodJson = typeof item.original === 'string' || typeof item.comment === 'string';

  // For Toadgod lore JSON, include BOTH original tweet + definition.
  const original = isToadgodJson ? String(item.original || '').trim() : '';
  const definition = isToadgodJson ? String(item.comment || '').trim() : '';

  // For scroll index mode, fall back to preview-ish fields.
  const fallbackBody = String(item.text_preview || item.summary || '').trim();

  const slotNames = ['Dawn Drop', 'Midday Drop', 'Evening Drop', 'Night Drop'];
  const slotLabel = slotNames[slot] || `Drop ${slot}`;

  const source = item.id || 'unknown';

  const lines = [
    `<b>🪷 ${escapeHtml(slotLabel)}</b>`,
    '',
    `<b>${escapeHtml(title)}</b>${date ? ` <i>(${escapeHtml(date)})</i>` : ''}`,
    ''
  ];

  if (isToadgodJson) {
    const o = trimTo(stripMarkdown(original), 420);
    const d = trimTo(stripMarkdown(definition), 900);

    lines.push(`<b>Original (Toadgod)</b>`);
    lines.push(o ? escapeHtml(o) : '<i>(missing)</i>');
    lines.push('');
    lines.push(`<b>Definition</b>`);
    lines.push(d ? escapeHtml(d) : '<i>(missing)</i>');
  } else {
    const b = trimTo(stripMarkdown(fallbackBody), 900);
    lines.push(b ? escapeHtml(b) : '<i>(no excerpt available)</i>');
  }

  lines.push('');
  lines.push(`<i>Source</i>: <code>${escapeHtml(source)}</code>`);

  return lines.join('\n');
}

function escapeHtml(s) {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function stripMarkdown(s) {
  // Very lightweight cleanup so tweet-style markdown doesn't overwhelm Telegram.
  return String(s || '')
    .replace(/^#+\s+/gm, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`([^`]*)`/g, '$1')
    .replace(/>\s?/g, '')
    .trim();
}

function trimTo(s, maxLen) {
  const t = String(s || '').trim();
  if (!maxLen || t.length <= maxLen) return t;
  return t.slice(0, maxLen).trimEnd() + '…';
}

async function sendTelegram(token, chatId, text) {
  const url = `https://api.telegram.org/bot${token}/sendMessage`;
  try {
    await axios.post(url, {
      chat_id: chatId,
      text,
      parse_mode: 'HTML',
      disable_web_page_preview: true
    }, { timeout: 20000 });
  } catch (e) {
    const status = e?.response?.status;
    const desc = e?.response?.data?.description;
    throw new Error(`Telegram API error ${status || ''}${desc ? `: ${desc}` : ''}`.trim());
  }
}

async function main() {
  const token = process.env.TELEGRAM_TOKEN;
  const chatId = process.env.TELEGRAM_CHAT_ID;
  if (!token) fail('Missing TELEGRAM_TOKEN');
  if (!chatId) fail('Missing TELEGRAM_CHAT_ID');

  const slot = Number.isFinite(parseInt(process.env.DROP_SLOT, 10)) ? parseInt(process.env.DROP_SLOT, 10) : 0;

  const sourceMode = (process.env.DROP_SOURCE || 'toadgod_json').toLowerCase();

  let items;
  if (sourceMode === 'toadgod_json') {
    const lorePath = path.join(process.cwd(), 'lore', 'toadgod-lore.json');
    if (!fs.existsSync(lorePath)) fail(`Missing lore/toadgod-lore.json: ${lorePath}`);
    try {
      items = JSON.parse(fs.readFileSync(lorePath, 'utf8'));
    } catch (e) {
      fail(`Could not parse lore/toadgod-lore.json: ${e.message}`);
    }
  } else if (sourceMode === 'scroll_index') {
    const idxPath = process.env.SCROLL_INDEX || path.join(process.cwd(), 'data', 'scroll_index.json');
    if (!fs.existsSync(idxPath)) fail(`Missing scroll index: ${idxPath} (run index rebuild first)`);
    try {
      items = JSON.parse(fs.readFileSync(idxPath, 'utf8'));
    } catch (e) {
      fail(`Could not parse scroll index JSON: ${e.message}`);
    }
  } else {
    fail(`Unknown DROP_SOURCE: ${sourceMode}. Use 'toadgod_json' or 'scroll_index'.`);
  }

  if (!Array.isArray(items) || items.length === 0) fail('Lore source is empty or invalid');

  const { item } = pickItem(items, slot);
  const text = formatMessage({ item, slot });
  await sendTelegram(token, chatId, text);

  console.log(`Sent Telegram lore drop (slot=${slot}, source=${sourceMode}) using ${item.id || item.path || 'unknown'}`);
}

main().catch((e) => {
  console.error('FAILED:', e?.message || e);
  process.exit(1);
});
